option(ENABLE_OPENAXIS "Enable OpenAxis navigation" OFF)
set(OPENAXIS_SOURCE_DIR "" CACHE PATH "Local OpenAxis SDK checkout")
if(ENABLE_OPENAXIS)
  if(HEADLESS)
    message(FATAL_ERROR "OpenAxis requires the GUI")
  endif()
  if(CMAKE_VERSION VERSION_LESS 3.24)
    message(FATAL_ERROR "OpenAxis requires CMake 3.24 or newer")
  endif()
  set(CMAKE_POSITION_INDEPENDENT_CODE ON)
  set(OPENAXIS_BUILD_TESTS OFF CACHE BOOL "Build SDK tests")
  set(OPENAXIS_BUILD_DEMO OFF CACHE BOOL "Build SDK demo")
  if(OPENAXIS_SOURCE_DIR)
    add_subdirectory("${OPENAXIS_SOURCE_DIR}/cpp" "${CMAKE_BINARY_DIR}/openaxis")
  else()
    include(FetchContent)
    FetchContent_Declare(openaxis
      GIT_REPOSITORY https://github.com/rotatrix/openaxis.git
      GIT_TAG acc4da095cde6747556245b4b6c110c16b968b6b
      SOURCE_SUBDIR cpp)
    FetchContent_MakeAvailable(openaxis)
  endif()
  target_sources(OpenSCADLibInternal PRIVATE src/gui/OpenAxisController.cc)
  target_compile_definitions(OpenSCADLibInternal PUBLIC ENABLE_OPENAXIS)
  target_link_libraries(OpenSCADLibInternal PUBLIC OpenAxis::openaxis)
  if(ENABLE_TESTS)
    add_executable(OpenAxisCameraTests tests/openaxis/camera.cc)
    target_include_directories(OpenAxisCameraTests PRIVATE src)
    target_link_libraries(OpenAxisCameraTests PRIVATE Eigen3::Eigen OpenAxis::openaxis)
    add_test(NAME openaxis_camera COMMAND OpenAxisCameraTests)
    add_executable(OpenAxisOverlayTests tests/openaxis/overlay.cc)
    target_include_directories(OpenAxisOverlayTests PRIVATE src)
    if(USE_QT6)
      target_link_libraries(OpenAxisOverlayTests PRIVATE OpenAxis::openaxis Qt6::Widgets)
    else()
      target_link_libraries(OpenAxisOverlayTests PRIVATE OpenAxis::openaxis Qt5::Widgets)
    endif()
    add_test(NAME openaxis_overlay COMMAND OpenAxisOverlayTests)
    set_tests_properties(openaxis_overlay PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
  endif()
endif()
