option(ENABLE_OPENAXIS "Enable OpenAxis navigation" OFF)
set(OPENAXIS_SOURCE_DIR "" CACHE PATH "Local OpenAxis SDK checkout")
if(ENABLE_OPENAXIS)
  if(HEADLESS)
    message(FATAL_ERROR "OpenAxis requires the GUI")
  endif()
  if(CMAKE_VERSION VERSION_LESS 3.24)
    message(FATAL_ERROR "OpenAxis requires CMake 3.24 or newer")
  endif()
  set(CMAKE_POSITION_INDEPENDENT_CODE ON)
  set(OPENAXIS_BUILD_TESTS OFF CACHE BOOL "Build SDK tests")
  set(OPENAXIS_BUILD_DEMO OFF CACHE BOOL "Build SDK demo")
  if(OPENAXIS_SOURCE_DIR)
    add_subdirectory("${OPENAXIS_SOURCE_DIR}/cpp" "${CMAKE_BINARY_DIR}/openaxis")
  else()
    include(FetchContent)
    FetchContent_Declare(openaxis
      GIT_REPOSITORY https://github.com/rotatrix/openaxis.git
      GIT_TAG acc4da095cde6747556245b4b6c110c16b968b6b
      SOURCE_SUBDIR cpp)
    FetchContent_MakeAvailable(openaxis)
  endif()
  target_sources(OpenSCADLibInternal PUBLIC src/gui/OpenAxisController.cc)
  target_compile_definitions(OpenSCADLibInternal PUBLIC ENABLE_OPENAXIS)
  target_link_libraries(OpenSCADLibInternal PUBLIC OpenAxis::openaxis)
endif()
